name: ${MAIL_SUBDOMAIN_NAME}

services:
  postfix:
    container_name: ${MAIL_SUBDOMAIN_NAME}-postfix
    hostname: ${MAIL_SUBDOMAIN_NAME}
    build:
      context: ./postfix
      network: host
    network_mode: "host"
    volumes:
      - ${SSL_CERTIFICATE_LOCATION}:/etc/letsencrypt/live/rhthr.com:ro
    env_file:
      - .env
  dovecot:
    container_name: ${MAIL_SUBDOMAIN_NAME}-dovecot
    hostname: ${MAIL_SUBDOMAIN_NAME}
    build:
      context: ./dovecot
      network: host
    network_mode: "host"
    volumes:
      - ${SSL_CERTIFICATE_LOCATION}:/etc/letsencrypt/live/rhthr.com:ro
    env_file:
      - .env