dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.1
!include_try /usr/share/dovecot/protocols.d/*.protocol
instance_name = dovecot
login_greeting = "Dovecot ready."
login_trusted_networks = 0.0.0.0/0 ::0
!include conf.d/*.conf
!include_try local.conf
auth_verbose = yes
login_log_format_elements = "user=<%u> method=%m rip=%r lip=%l mpid=%e %c %k"